//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NumberGuessGameService.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.INumberGuessGameService")]
    public interface INumberGuessGameService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INumberGuessGameService/SecretNumber", ReplyAction="http://tempuri.org/INumberGuessGameService/SecretNumberResponse")]
        int SecretNumber(int lower, int upper);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INumberGuessGameService/SecretNumber", ReplyAction="http://tempuri.org/INumberGuessGameService/SecretNumberResponse")]
        System.Threading.Tasks.Task<int> SecretNumberAsync(int lower, int upper);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INumberGuessGameService/CheckNumber", ReplyAction="http://tempuri.org/INumberGuessGameService/CheckNumberResponse")]
        string CheckNumber(int userNum, int secretNum);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INumberGuessGameService/CheckNumber", ReplyAction="http://tempuri.org/INumberGuessGameService/CheckNumberResponse")]
        System.Threading.Tasks.Task<string> CheckNumberAsync(int userNum, int secretNum);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface INumberGuessGameServiceChannel : NumberGuessGameService.ServiceReference1.INumberGuessGameService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class NumberGuessGameServiceClient : System.ServiceModel.ClientBase<NumberGuessGameService.ServiceReference1.INumberGuessGameService>, NumberGuessGameService.ServiceReference1.INumberGuessGameService {
        
        public NumberGuessGameServiceClient() {
        }
        
        public NumberGuessGameServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public NumberGuessGameServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public NumberGuessGameServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public NumberGuessGameServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int SecretNumber(int lower, int upper) {
            return base.Channel.SecretNumber(lower, upper);
        }
        
        public System.Threading.Tasks.Task<int> SecretNumberAsync(int lower, int upper) {
            return base.Channel.SecretNumberAsync(lower, upper);
        }
        
        public string CheckNumber(int userNum, int secretNum) {
            return base.Channel.CheckNumber(userNum, secretNum);
        }
        
        public System.Threading.Tasks.Task<string> CheckNumberAsync(int userNum, int secretNum) {
            return base.Channel.CheckNumberAsync(userNum, secretNum);
        }
    }
}
